### ISSUE TITLE
Never subtract, even on empty wallet

### ISSUE THREAD

**Issue by wtogami** [Litecoin-Java/bitcoin-wallet#10]
https://github.com/Litecoin-Java/bitcoin-wallet/commit/6119facbbee98613720ecc4307c18eb1245279d6
Much better!

I recommend not subtracting on the empty wallet case.  Why?  It is confusing for the Send dialog to say one number but it changes in the confirm dialog.  Make it behave like any other send.  Consistency in all situations would be better I think.

Also have you tested what happens in the empty case if there is insufficient funds to empty?

**Comment by wtogami** [comment]
A possible alternative would be for Empty Wallet use completeTx to calculate the actual fee before filling out the Send field.  For that to work they would need to select a To address before Empty Wallet is selected, or you would need to use a temporary dummy address in the To field before completeTx will be able to calculate the fee.  In the latter case care must be taken that it is replaced with a user selected address before the next completeTx for the confirmation dialog.

**Comment by hank** [comment]
Good point on insufficient funds to empty - we have to try that.
Perhaps I could make it so the insufficient funds dialog would offer to adjust the amount.  I'll play with that..

**Comment by hank** [comment]
Oh and what do we do about the bug in bitcoinj that produces a 0 fee on empty?  That's the whole reason for the empty case - it will make a valid TX to confirm that has 0 fee without the subtraction of MIN_TX_FEE.

**Comment by hank** [comment]
Change 8461b5736b83510f9e0e8f5b04bb317d6ee76dda confirms everything with the user, so it's very plain what's happening.  Please validate current behavior makes sense, and if it does, close this.  If not, comment.

**Comment by wtogami** [comment]
In the long-run we will need to override stuff and ask upstream to abstract more things to make it easier for overrides to be smaller.

**Comment by hank** [comment]
I agree - if they fixed the zero-fee empty issue, I could get rid of some code.  The dust outputs issue should also be ported in bitcoinj as an abstract method that bitcoin and litecoin can override in different ways.  Sadly, I'm not really sure if there's a better way to handle the other cases - we have to confirm extra fees and confirm fees on wallet empty no matter where the code is.  This works for now though I think - close?
