### ISSUE TITLE
Google Drive wallet backup, download opens wrong app

### ISSUE THREAD

**Issue by wtogami** [Litecoin-Java/bitcoin-wallet#14]
1. Backup to Google Drive.
2. Open the "Litecoin Wallet private key backup" from Google Drive.
3. It opens the Bitcoin Wallet instead of Litecoin app...

(Downloading from Gmail gives you an option of which app you want to open.  Drive does not.)

**Comment by hank** [comment]
This is odd - I can reproduce it, but I don't know what causes it.  Bitcoin doesn't have any associations listed in the app settings menu on my tablet, so there's no "default" to clear.  The file has no extension, and is composed a just a Base64 string - perhaps there's some association with the base64-ed version of "Salted__" which is what the file begins with (magic number).

**Comment by hank** [comment]
Fixed - wrong mimeType on export.  Verified it works in Google Wallet.
