### ISSUE TITLE
USD rate not updating

### ISSUE THREAD

**Issue by wtogami** [Litecoin-Java/bitcoin-wallet#16]
The app is showing me $25.7350 while BTC-e is $29.345.

**Comment by hank** [comment]
Perhaps it was pulling from Cryptsy.  I'll check how often the exchange is supposed to update - Andreas completely rewrote that part of the wallet app.

**Comment by hank** [comment]
69dcc43da182fec811b109222923080831ff3285 has code that pulls exchange rates for a bunch of currencies from Yahoo!.  It seems to work well here, and I think I got all the error handling in so if it fails, the app doesn't crash.  At a minimum, you should get LTCUSD from either BTC-E or cryptsy.  You can see which by tapping the rate in the exchange rate viewer.

**Comment by hank** [comment]
Also, this:

``` java
    private static final long UPDATE_FREQ_MS = 10 * DateUtils.MINUTE_IN_MILLIS;
```

Seems sufficient.  If it doesn't update for you still, let me know.
