### ISSUE TITLE
I'd like to use QR Droid to scan QR Code

### ISSUE THREAD

**Issue by Nogreedy** [Litecoin-Java/bitcoin-wallet#17]
I'd like to use QR Droid (Google play_Android app of course) to scan QR Code (as I do with Blockchain Android app for BTC) but Litecoin Android ask me to install Barcode Scanner when I want to scan QR code to send LTC to adress...

**Comment by hank** [comment]
http://code.google.com/p/zxing/source/browse/trunk/android-integration/src/main/java/com/google/zxing/integration/android/IntentIntegrator.java#86

<p>By default, this will only allow applications that are known to respond to this intent correctly
 * do so. The apps that are allowed to response can be set with {@link #setTargetApplications(List)}.
 * For example, set to {@link #TARGET_BARCODE_SCANNER_ONLY} to only target the Barcode Scanner app itself.</p>

http://www.openintents.org/node/840
To use QR Droid services, you must simply create an Intent with one of these actions:
la.droid.qr.scan
la.droid.qr.encode
la.droid.qr.decode

Should be easy.
