### ISSUE TITLE
Add support for encrypted paper wallets

### ISSUE THREAD

**Issue by adv0r** [Litecoin-Java/bitcoin-wallet#19]
I would like to see state-of-the-art encryption/decryption functionalities for private keys printed on paper wallets.

**Comment by hank** [comment]
So you mean import of BIP0038 paper wallets?

**Comment by adv0r** [comment]
yes sir

On Wed, Jan 8, 2014 at 3:00 PM, hank notifications@github.com wrote:

> So you mean import and export of BIP0038 paper wallets?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Litecoin-Java/bitcoin-wallet/issues/19#issuecomment-31832856
> .

## 

❝  Nicolò Paternoster
☎  +34 603.678.719
ଭ  adva.io
B⃦   1337AdvApU14cW4M8fU5E1zAqDEe4NZGGN

**Comment by wtogami** [comment]
This really is the type of feature that needs to happen in the upstream bitcoin-walllet before it is possible here.  This is a very non-trivial amount of work.

**Comment by adv0r** [comment]
It is supported on block chain. Info
