### ISSUE TITLE
Correct/remove things from About

### ISSUE THREAD

**Issue by wtogami** [Litecoin-Java/bitcoin-wallet#2]
- Merge on top of upstream 3.29 to get many translation updates.
- Add "Copyright 2014 Litecoin Dev Team" on the same line after Andreas Schildbach
- Twitter @bitcoin_wallet -> @LitecoinProject
- Author at Google+, change the title to "+LitecoinProject"
- Remove "Other Apps of Author"
- Remove "This app is using an icon by 'bitboy'"

**Comment by hank** [comment]
Awesome - I don't think merging with upstream should be all that bad - I was doing a bit of that in the last fork, and conflicts + incompatible changes were minimal.

**Comment by hank** [comment]
Everything here is done, except the merge, which is #4
