### ISSUE TITLE
xxhdpi Litecoin icon looks washed out

### ISSUE THREAD

**Issue by wtogami** [Litecoin-Java/bitcoin-wallet#30]
![side-by-side](https://f.cloud.github.com/assets/93665/1906786/8c6f27a8-7cb9-11e3-9071-209da2dadf85.png)

Left is the new Litecoin app.  Right is the old Litecoin app.

On the Nexus 7 (2013) newer apps display the xxhdpi icon.  It would look better if the icon looked bold like the old icon.

**Comment by hank** [comment]
cfc2f34511fb4631e834b94901ecb104c9d78beb fixes this.
