### ISSUE TITLE
Not explicit address name to check transaction on explorer.litecoin.net

### ISSUE THREAD

**Issue by Nogreedy** [Litecoin-Java/bitcoin-wallet#31]
The link to check transaction to http://explorer.litecoin.net works well but it isn't explicit.
The link indicates "@2131427582" (see screencapture below).
Perhaps this issue is only for app french version (v. 3.29.3).

![sc20140114-092756](https://f.cloud.github.com/assets/6340683/1947190/85b9f4dc-8043-11e3-978d-512b538c5373.png)

**Comment by hank** [comment]
This is a carryover from Bitcoin Wallet - the source of that number will have to be looked at (it looks suspiciously like INT_MAX to me).  Perhaps we should put a localized string of "Explorer" there...

Thanks!

**Comment by hank** [comment]
ef7199ed8476ba9ac42b0149aa78cd949b4ca256 fixes this, and adds an alternative explorer to the menu as well for when one explorer is broken.
