### ISSUE TITLE
Safety notes web view is not properly wrapped by its DialogFragment container.

### ISSUE THREAD

**Issue by santa4nt** [Litecoin-Java/bitcoin-wallet#35]
The webview, which is loaded by HelpDialogFragment using the "safety" page, does not seem to be properly wrapped by the fragment container. Noticed on Nexus 5 phone and Nexus 4 emulator:

![device-2014-01-20-172626](https://f.cloud.github.com/assets/152710/1959618/2aa0956e-8233-11e3-865b-8f22aa3d575c.png)

On that note, why do we have these *.html pages in assets/, along with its translation in its own localization scheme? Shouldn't these be in res/ as first-class Android resources?

**Comment by hank** [comment]
The comment about HTML is interesting.  They probably should be in res.  The only problem with that is it would diverge greatly with the upstream layout, and we'd have to remember to delete them / update them all the time since git wouldn't merge the changes if we move them.

I'll check this out soon, or someone else is welcome to fix it and submit a pull request.

**Comment by hank** [comment]
I think the above addresses everything in this ticket.  Closing.

**Comment by hank** [comment]
Also, the reason it was like this before was probably because API level < 8 didn't support locale-specific raw resources.

**Comment by santa4nt** [comment]
Curiously, the upstream Bitcoin wallet app does not seem to exhibit the
weird UI wrapping behavior, though.

**Comment by hank** [comment]
Oh yes that's true because of this:

37335de1f4a320896b0d841ac1196e24680dce08

pre was a bad choice.

**Comment by santa4nt** [comment]
FWIW, it seems that upstream, they also have moved the clunky assets/ html texts to its own resource silo:

https://github.com/schildbach/bitcoin-wallet/blob/master/wallet/res/values/strings_help.xml

**Comment by hank** [comment]
Interesting!  We'll probably just convert to that next time we pull upstream, and blow away all the html files.
