### ISSUE TITLE
v3.30.1 not a clean build?

### ISSUE THREAD

**Issue by santa4nt** [Litecoin-Java/bitcoin-wallet#40]
Seems like the build for v3.30.1 in the Play Store got mixed up with old resources?

Here's what I get from a cloned check out build:

![device-2014-01-24-214058](https://f.cloud.github.com/assets/152710/2001046/9c78e0e4-8583-11e3-9f08-c5a4d58d68e9.png)

Here's what I get from the Play Store:

![screenshot_2014-01-24-21-41-31](https://f.cloud.github.com/assets/152710/2001048/a6f4189a-8583-11e3-8875-2d869f0ef0bd.png)

**Comment by santa4nt** [comment]
The `<ul><li>` tags are telling since they should not be present in the latest revision of strings_help.xml resource.

**Comment by hank** [comment]
That's odd.. looking into it.

**Comment by hank** [comment]
Just rebuilt as 3.30.2 and put in Play Beta.  Please try as soon as it hits.  Thanks!

**Comment by santa4nt** [comment]
How does one get into Play Beta?

Also, this might be why: the Play Store "What's New" listing has been updated to 3.30.2 (and 3.30.1 previously) but the "Current Version" still says:

```
Current Version
3.29.4
```

**Comment by hank** [comment]
The beta is accessible using these instructions:

https://litecointalk.org/index.php?topic=12196.msg90759#msg90759

**Comment by santa4nt** [comment]
Right. Done. I see it fixed now.
