### ISSUE TITLE
Importing Keys

### ISSUE THREAD

**Issue by ss44** [Litecoin-Java/bitcoin-wallet#41]
Importing keys from litecoin-qt seems to throw an error, with the keys being invalid or corrupt.

**Comment by hank** [comment]
How did you dump the wallet backup?  I'll try to reproduce.

**Comment by hank** [comment]
I just dumped my wallet, dumped the backup with openssl, and imported every key into a brand new freshly downloaded litecoin-qt.  Worked fine.  All private keys start with T or 6.  What are you seeing as the first character?

**Comment by hank** [comment]
Wait - importing keys?  You mean dumping them from litecoin-qt and importing them into the app?  How are you trying to do that?

**Comment by hank** [comment]
Just tried putting an address into my mirror of https://liteaddress.org/ and scanning the Private Key WIF QR code, and it imported fine.

**Comment by ss44** [comment]
Turns out I may have completely wasted your time with this one. Sorry about that. I was trying to import a backed up wallet (dat file) and when clicking on the link it was offering Litecoin wallet as an app that could read it. I incorrectly assumed this was saving copies of the private key.

**Comment by hank** [comment]
Ohhh right OK.  It would be nice to be able to import a wallet.dat, but AFAIK that doesn't work.  To do that, I'd recommend doing dumpprivkey on the addresses desired in QT and putting those in liteaddress (or a mirror) to generate QR codes, then scanning those with the app.

Thanks for testing this - no hard feelings!
