### ISSUE TITLE
Own dnsseeds

### ISSUE THREAD

**Issue by UngarnFCP** [Litecoin-Java/bitcoin-wallet#65]
When I want to add own dnsseeds do they need a special litecoin.conf or can the app also talk to my local laptop which I use for Litecoin without any special changes?

At https://litecointalk.org/index.php?topic=5330.0 for example a guy describes a bloomfilters=1 setting.

Can the app communicate also with other dnsseeds that do not have this bloomfilter enabled by default?

**Comment by hank** [comment]
When you say you want to "add your own dnsseeds" what do you mean?  A DNS seed is simply a server that serves up a dynamic DNS record containing peer addresses.  Adding another DNS seed would require re-compiling the wallet.  The wallet uses the same DNS seeds that the official client uses.  

You can use the Trusted Peer setting in the options to make the app peer with your laptop (even exclusively).  I believe Bloom Filters are currently turned off in the wallet, but I'd have to go back and check.  As the post says, they would be convenient for SPV wallets, but we don't require them.  As you can see, the default for the official client leaves them off, so we can't depend on them.
