### ISSUE TITLE
Bitcoinj missing

### ISSUE THREAD

**Issue by nejcokorn** [Litecoin-Java/bitcoin-wallet#70]
[INFO] ------------------------------------------------------------------------
[INFO] Building Bitcoin Wallet 3.29-test
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.google:bitcoinj:jar:0.10.3 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] base .............................................. SUCCESS [  0.493 s]
[INFO] Bitcoin Integration for Android ................... SUCCESS [  1.782 s]
[INFO] Bitcoin Wallet .................................... FAILURE [  0.263 s]
[INFO] Sample for Bitcoin Integration for Android ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.998 s
[INFO] Finished at: 2014-10-06T14:35:24+01:00
[INFO] Final Memory: 23M/180M
[INFO] ------------------------------------------------------------------------

I also noticed i could not download anything from

https://code.google.com/p/bitcoinj/source/browse/releases/com/google/bitcoinj/0.10.3/?repo=distribution&r=374786d19ca0e4cd44e828a7245033c7a8d0e766

Error: NET::ERR_CERT_COMMON_NAME_INVALID

Am i missing something?

Tnx for your help.

**Comment by hank** [comment]
Build this first and install it with maven:

https://github.com/Litecoin-Java/bitcoinj

Then build the wallet against it.
